"""Refresh the pinned list of Cloudflare's edge addresses.

app/core/cloudflare_ranges.py is generated by this script: the address
ranges Cloudflare publishes for its edge, from which a request's
CF-Connecting-IP header is believed (app.core.client_ip). Pinned rather
than fetched at startup, so the server never depends on Cloudflare's API to
boot and a change to the list is a reviewed commit.

    python -m scripts.refresh_cloudflare_ranges           # rewrite the module
    python -m scripts.refresh_cloudflare_ranges --check   # exit 1 if it is stale

Cloudflare changes the list rarely and announces it; refresh it when they
do, and at least with the monthly dependency review (docs/process.md).
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import sys
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

SOURCE = "https://api.cloudflare.com/client/v4/ips"
MODULE = Path(__file__).resolve().parents[1] / "app" / "core" / "cloudflare_ranges.py"


def fetch() -> list[str]:
    """Cloudflare's current ranges, IPv4 then IPv6, each validated."""
    with urllib.request.urlopen(SOURCE, timeout=30) as response:  # noqa: S310 (a fixed https URL)
        body = json.load(response)
    if not body.get("success"):
        raise SystemExit(f"Cloudflare's API answered without success: {body.get('errors')}")
    result = body["result"]
    ranges = [*result["ipv4_cidrs"], *result["ipv6_cidrs"]]
    # A range that does not parse must never reach the trusted list.
    return [str(ipaddress.ip_network(cidr, strict=True)) for cidr in ranges]


def render(ranges: list[str], fetched: str) -> str:
    lines = "\n".join(f'    "{cidr}",' for cidr in ranges)
    return (
        '"""Cloudflare\'s published edge address ranges. GENERATED: do not edit.\n'
        "\n"
        "Written by scripts/refresh_cloudflare_ranges.py from\n"
        f"{SOURCE} (fetched {fetched}). A request that\n"
        "reached the proxies from one of these came through Cloudflare, so its\n"
        "CF-Connecting-IP header names the visitor (app.core.client_ip).\n"
        '"""\n'
        "\n"
        "CLOUDFLARE_RANGES: tuple[str, ...] = (\n"
        f"{lines}\n"
        ")\n"
    )


def pinned() -> list[str]:
    """The ranges the committed module holds."""
    namespace: dict[str, object] = {}
    exec(MODULE.read_text(encoding="utf-8"), namespace)  # noqa: S102 (our own generated file)
    return list(namespace["CLOUDFLARE_RANGES"])  # type: ignore[arg-type]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the pinned list differs")
    args = parser.parse_args(argv)
    current = fetch()
    if args.check:
        if sorted(current) == sorted(pinned()):
            print("cloudflare ranges are current")
            return 0
        print("cloudflare ranges changed: run python -m scripts.refresh_cloudflare_ranges")
        return 1
    MODULE.write_text(render(current, datetime.now(UTC).date().isoformat()), encoding="utf-8")
    print(f"wrote {len(current)} ranges to {MODULE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
