"""The ARPABET inventory and the exception lexicon: words English spelling
lies about, which no rule should be asked to get right."""

from __future__ import annotations

VOWEL_PHONEMES = frozenset("AA AE AH AO AW AY EH ER EY IH IY OW OY UH UW".split())
CONSONANT_PHONEMES = frozenset("B CH D DH F G HH JH K L M N NG P R S SH T TH V W Y Z ZH".split())
PHONEMES = VOWEL_PHONEMES | CONSONANT_PHONEMES
VOICED_CONS = frozenset("B D DH G JH L M N NG R V W Y Z ZH".split())
SIBILANTS = frozenset("S Z SH ZH CH JH".split())

LEXICON_RAW = {
    "a": "AH",
    "the": "DH AH",
    "of": "AH V",
    "to": "T UW",
    "and": "AE N D",
    "is": "IH Z",
    "as": "AE Z",
    "are": "AA R",
    "was": "W AH Z",
    "were": "W ER",
    "be": "B IY",
    "been": "B IH N",
    "being": "B IY IH NG",
    "am": "AE M",
    "one": "W AH N",
    "two": "T UW",
    "once": "W AH N S",
    "only": "OW N L IY",
    "said": "S EH D",
    "says": "S EH Z",
    "say": "S EY",
    "do": "D UW",
    "does": "D AH Z",
    "done": "D AH N",
    "doing": "D UW IH NG",
    "have": "HH AE V",
    "has": "HH AE Z",
    "had": "HH AE D",
    "having": "HH AE V IH NG",
    "come": "K AH M",
    "comes": "K AH M Z",
    "coming": "K AH M IH NG",
    "some": "S AH M",
    "gone": "G AO N",
    "go": "G OW",
    "goes": "G OW Z",
    "going": "G OW IH NG",
    "none": "N AH N",
    "who": "HH UW",
    "whom": "HH UW M",
    "whose": "HH UW Z",
    "what": "W AH T",
    "where": "W EH R",
    "there": "DH EH R",
    "their": "DH EH R",
    "they": "DH EY",
    "them": "DH EH M",
    "then": "DH EH N",
    "than": "DH AE N",
    "this": "DH IH S",
    "that": "DH AE T",
    "these": "DH IY Z",
    "those": "DH OW Z",
    "though": "DH OW",
    "through": "TH R UW",
    "thought": "TH AO T",
    "throughout": "TH R UW AW T",
    "people": "P IY P AH L",
    "because": "B IH K AO Z",
    "would": "W UH D",
    "could": "K UH D",
    "should": "SH UH D",
    "again": "AH G EH N",
    "against": "AH G EH N S T",
    "women": "W IH M AH N",
    "woman": "W UH M AH N",
    "many": "M EH N IY",
    "any": "EH N IY",
    "every": "EH V R IY",
    "very": "V EH R IY",
    "you": "Y UW",
    "your": "Y AO R",
    "yours": "Y AO R Z",
    "our": "AW ER",
    "hour": "AW ER",
    "honest": "AA N AH S T",
    "honor": "AA N ER",
    "know": "N OW",
    "knows": "N OW Z",
    "knew": "N UW",
    "known": "N OW N",
    "new": "N UW",
    "now": "N AW",
    "how": "HH AW",
    "cow": "K AW",
    "allow": "AH L AW",
    "own": "OW N",
    "shown": "SH OW N",
    "grown": "G R OW N",
    "thrown": "TH R OW N",
    "down": "D AW N",
    "town": "T AW N",
    "write": "R AY T",
    "wrote": "R OW T",
    "written": "R IH T AH N",
    "wrong": "R AO NG",
    "walk": "W AO K",
    "talk": "T AO K",
    "half": "HH AE F",
    "laugh": "L AE F",
    "enough": "IH N AH F",
    "tough": "T AH F",
    "rough": "R AH F",
    "cough": "K AO F",
    "bought": "B AO T",
    "brought": "B R AO T",
    "ought": "AO T",
    "love": "L AH V",
    "above": "AH B AH V",
    "move": "M UW V",
    "prove": "P R UW V",
    "give": "G IH V",
    "gives": "G IH V Z",
    "given": "G IH V AH N",
    "giving": "G IH V IH NG",
    "live": "L IH V",
    "lives": "L IH V Z",
    "living": "L IH V IH NG",
    "get": "G EH T",
    "gets": "G EH T S",
    "getting": "G EH T IH NG",
    "girl": "G ER L",
    "gift": "G IH F T",
    "begin": "B IH G IH N",
    "together": "T AH G EH DH ER",
    "forget": "F ER G EH T",
    "good": "G UH D",
    "food": "F UW D",
    "blood": "B L AH D",
    "flood": "F L AH D",
    "door": "D AO R",
    "floor": "F L AO R",
    "poor": "P UH R",
    "four": "F AO R",
    "sure": "SH UH R",
    "sugar": "SH UH G ER",
    "school": "S K UW L",
    "machine": "M AH SH IY N",
    "chef": "SH EH F",
    "ache": "EY K",
    "echo": "EH K OW",
    "character": "K EH R IH K T ER",
    "stomach": "S T AH M AH K",
    "ocean": "OW SH AH N",
    "christmas": "K R IH S M AH S",
    "eye": "AY",
    "eyes": "AY Z",
    "key": "K IY",
    "money": "M AH N IY",
    "month": "M AH N TH",
    "mother": "M AH DH ER",
    "father": "F AA DH ER",
    "brother": "B R AH DH ER",
    "other": "AH DH ER",
    "another": "AH N AH DH ER",
    "son": "S AH N",
    "won": "W AH N",
    "nothing": "N AH TH IH NG",
    "something": "S AH M TH IH NG",
    "front": "F R AH N T",
    "friend": "F R EH N D",
    "heart": "HH AA R T",
    "earth": "ER TH",
    "early": "ER L IY",
    "earn": "ER N",
    "learn": "L ER N",
    "heard": "HH ER D",
    "here": "HH IY R",
    "hear": "HH IH R",
    "world": "W ER L D",
    "work": "W ER K",
    "word": "W ER D",
    "worse": "W ER S",
    "worth": "W ER TH",
    "water": "W AO T ER",
    "watch": "W AA CH",
    "want": "W AA N T",
    "put": "P UH T",
    "push": "P UH SH",
    "bush": "B UH SH",
    "pull": "P UH L",
    "busy": "B IH Z IY",
    "business": "B IH Z N AH S",
    "buy": "B AY",
    "build": "B IH L D",
    "built": "B IH L T",
    "break": "B R EY K",
    "great": "G R EY T",
    "steak": "S T EY K",
    "bread": "B R EH D",
    "head": "HH EH D",
    "dead": "D EH D",
    "death": "D EH TH",
    "breath": "B R EH TH",
    "breathe": "B R IY DH",
    "ready": "R EH D IY",
    "already": "AO L R EH D IY",
    "health": "HH EH L TH",
    "weather": "W EH DH ER",
    "measure": "M EH ZH ER",
    "pleasure": "P L EH ZH ER",
    "island": "AY L AH N D",
    "answer": "AE N S ER",
    "sword": "S AO R D",
    "lamb": "L AE M",
    "climb": "K L AY M",
    "comb": "K OW M",
    "thumb": "TH AH M",
    "debt": "D EH T",
    "doubt": "D AW T",
    "listen": "L IH S AH N",
    "often": "AO F AH N",
    "castle": "K AE S AH L",
    "hundred": "HH AH N D R AH D",
    "why": "W AY",
    "which": "W IH CH",
    "while": "W AY L",
    "white": "W AY T",
    "whole": "HH OW L",
    "minute": "M IH N AH T",
    "use": "Y UW Z",
    "used": "Y UW Z D",
    "useful": "Y UW S F AH L",
    "first": "F ER S T",
    "sign": "S AY N",
    "science": "S AY AH N S",
    "eight": "EY T",
    "height": "HH AY T",
    "either": "IY DH ER",
    "neither": "N IY DH ER",
    "friends": "F R EH N D Z",
    "young": "Y AH NG",
    "touch": "T AH CH",
    "country": "K AH N T R IY",
    "couple": "K AH P AH L",
    "double": "D AH B AH L",
    "trouble": "T R AH B AH L",
    "southern": "S AH DH ER N",
    "among": "AH M AH NG",
    "company": "K AH M P AH N IY",
    "color": "K AH L ER",
    "cover": "K AH V ER",
    "monday": "M AH N D EY",
    "nose": "N OW Z",
    "rose": "R OW Z",
    "close": "K L OW Z",
    "chose": "CH OW Z",
    "choose": "CH UW Z",
    "lose": "L UW Z",
    "loose": "L UW S",
    "wise": "W AY Z",
    "please": "P L IY Z",
    "cause": "K AO Z",
    "both": "B OW TH",
    "most": "M OW S T",
    "post": "P OW S T",
    "journey": "JH ER N IY",
    "toward": "T AO R D",
    "course": "K AO R S",
    "over": "OW V ER",
    "open": "OW P AH N",
    "almost": "AO L M OW S T",
    "also": "AO L S OW",
    "always": "AO L W EY Z",
    "picture": "P IH K CH ER",
    "nature": "N EY CH ER",
    "future": "F Y UW CH ER",
    "receive": "R IH S IY V",
    "believe": "B IH L IY V",
    "piece": "P IY S",
    "field": "F IY L D",
    "tie": "T AY",
    "die": "D AY",
    "lie": "L AY",
    "pie": "P AY",
    "yes": "Y EH S",
    "us": "AH S",
    "his": "HH IH Z",
    "hers": "HH ER Z",
    "its": "IH T S",
    "i": "AY",
    "my": "M AY",
    "by": "B AY",
    "or": "AO R",
    "for": "F AO R",
    "nor": "N AO R",
    # contractions
    "i'm": "AY M",
    "i've": "AY V",
    "i'll": "AY L",
    "i'd": "AY D",
    "it's": "IH T S",
    "that's": "DH AE T S",
    "he's": "HH IY Z",
    "she's": "SH IY Z",
    "we're": "W IH R",
    "you're": "Y AO R",
    "they're": "DH EH R",
    "don't": "D OW N T",
    "won't": "W OW N T",
    "can't": "K AE N T",
    "isn't": "IH Z AH N T",
    "didn't": "D IH D AH N T",
    "doesn't": "D AH Z AH N T",
    "wasn't": "W AA Z AH N T",
    "couldn't": "K UH D AH N T",
    "wouldn't": "W UH D AH N T",
    "let's": "L EH T S",
    "shoe": "SH UW",
    "author": "AO TH ER",
    "method": "M EH TH AH D",
    "anger": "AE NG G ER",
    "angry": "AE NG G R IY",
    "knowledge": "N AA L IH JH",
    "worry": "W ER IY",
    "sorry": "S AA R IY",
}
LEXICON: dict[str, tuple[str, ...]] = {k: tuple(v.split()) for k, v in LEXICON_RAW.items()}
