"""Photographic mouth shapes, generated once per avatar.

The geometric mouth is a warp of one closed-mouth photo: it can open lips it
has, but it cannot invent teeth, a tongue, or the inside of a mouth that was
never photographed. That is the visible gap against hand-drawn avatar systems,
where an artist draws every viseme.

Here the artist is an image model, run ONCE at the user's request (it costs
money and takes a minute), producing a handful of keyframes of the same face
with different mouth shapes. The renderer then crossfades between them.

Three things make this work rather than produce a flickering collage:

1. The frames are keys in the SAME shape space the engine already computes.
   Every frame carries the blendshape coordinates of the viseme it depicts,
   so the existing coarticulation — timing, stress, dominance blending —
   is untouched: it still produces a continuous shape, and this only changes
   how that shape is drawn. No new timing model, nothing to re-tune.

2. Each frame is ALIGNED back to the original photo before being stored,
   using a similarity transform fitted to landmarks the mouth cannot move
   (eye corners, nose bridge). The model re-renders the whole face and never
   returns it in exactly the same place; without this the mouth patch would
   jump a few pixels every time the shape changed.

3. Only a feathered ellipse around the mouth is kept. The rest of the
   generated face — which drifts in identity, lighting and detail — is
   discarded. What survives is the one region that the original photo cannot
   provide and the model is good at.

A frame that fails any step is dropped, not patched: fewer good keys blend
better than one wrong one, and zero keys means the avatar simply keeps the
geometric mouth.
"""

from __future__ import annotations

import io
import json
import logging

logger = logging.getLogger("liveface.visemeframes")

# The keys worth paying for. Chosen to span the corners of the shape space
# rather than to cover every viseme: everything between them is a blend, and
# a mouth halfway to "open" genuinely looks like the average of closed and
# open. `sil` is included because a closed mouth generated by the same model
# under the same lighting matches its siblings better than the photo does.
KEY_VISEMES: dict[str, str] = {
    "sil": "lips gently closed in a neutral, relaxed resting position",
    "aa": "mouth open wide as if saying 'ah', jaw dropped, upper and lower teeth clearly apart, tongue visible low in the mouth",
    "E": "mouth open in a wide 'eh' shape, lips stretched horizontally, upper teeth visible",
    "oh": "lips rounded into an 'oh' shape, mouth open and circular, slightly pushed forward",
    "ou": "lips tightly pursed and pushed forward into a small 'oo' circle",
    "FF": "upper teeth resting lightly on the lower lip, as when saying 'f' or 'v'",
}

# Landmarks the mouth cannot move: outer eye corners and the nose bridge.
# The alignment fit uses only these, so a changed mouth cannot drag the
# transform toward itself.
STABLE_LANDMARKS = [33, 133, 263, 362, 168, 6, 197, 195]

# Mouth patch extent, as multiples of the mouth's own width/height.
PATCH_WIDTH = 1.5
PATCH_HEIGHT = 2.2
# How far the alignment may move the face before the frame is judged to be a
# different picture rather than the same one re-rendered.
MAX_ALIGN_SHIFT = 0.12  # of image width
MAX_ALIGN_SCALE = 0.18  # fractional deviation from 1.0


class VisemeFramesUnavailable(RuntimeError):
    """No image provider is configured, so frames cannot be generated."""


def _similarity(src: list[tuple[float, float]], dst: list[tuple[float, float]]):
    """Least-squares similarity transform (rotation+uniform scale+translation).

    Similarity, not affine: the face in the generated image is the same face
    at a slightly different size and position, and allowing shear would let
    the fit absorb genuine differences into a skew instead of reporting them.
    """
    import numpy as np

    s = np.asarray(src, dtype=np.float64)
    d = np.asarray(dst, dtype=np.float64)
    s_mean, d_mean = s.mean(axis=0), d.mean(axis=0)
    sc, dc = s - s_mean, d - d_mean
    var = (sc**2).sum()
    if var < 1e-9:
        return None
    cov = dc.T @ sc / len(s)
    u, sv, vt = np.linalg.svd(cov)
    rot = u @ vt
    if np.linalg.det(rot) < 0:
        vt[-1] *= -1
        rot = u @ vt
    scale = sv.sum() / (var / len(s))
    offset = d_mean - scale * (rot @ s_mean)
    return scale, rot, offset


def build_frame(generated: bytes, base_points, image_size) -> tuple[bytes, dict] | None:
    """Align a generated face to the base photo and cut out its mouth.

    Returns (png, geometry) or None when the frame cannot be trusted: no face
    found, or an alignment implying the model returned a different framing
    rather than the same face with a new mouth.
    """
    import numpy as np
    from PIL import Image

    from app.services.rig import landmarks_from_image

    try:
        points, _, size, detected = landmarks_from_image(generated)
    except Exception:
        logger.info("viseme frame: landmarking failed")
        return None
    if not detected:
        logger.info("viseme frame: no face in the generated image")
        return None

    base = np.asarray(base_points, dtype=np.float64)
    got = np.asarray(points, dtype=np.float64)
    fit = _similarity(
        [tuple(got[i]) for i in STABLE_LANDMARKS],
        [tuple(base[i]) for i in STABLE_LANDMARKS],
    )
    if fit is None:
        return None
    scale, rot, offset = fit

    width, height = image_size
    if abs(scale - 1.0) > MAX_ALIGN_SCALE:
        logger.info("viseme frame: scale %.3f out of range", scale)
        return None
    if float(np.hypot(*offset)) > width * MAX_ALIGN_SHIFT:
        logger.info("viseme frame: alignment shift too large")
        return None

    # Warp the generated image into the base photo's frame. PIL's AFFINE
    # takes the INVERSE map (destination -> source), which is what the
    # inverted similarity below produces.
    inv_scale = 1.0 / scale
    inv_rot = rot.T
    a = inv_scale * inv_rot
    b = -a @ offset
    image = Image.open(io.BytesIO(generated)).convert("RGB")
    if image.size != (size[0], size[1]):
        image = image.resize((size[0], size[1]))
    aligned = image.transform(
        (width, height),
        Image.AFFINE,
        (a[0, 0], a[0, 1], b[0], a[1, 0], a[1, 1], b[1]),
        resample=Image.BICUBIC,
    )

    # The patch box comes from the BASE mouth, so every frame shares one box
    # and the renderer can stack them without per-frame bookkeeping.
    from app.services.rig import MOUTH_INDICES

    mouth = base[MOUTH_INDICES]
    mcx, mcy = float(mouth[:, 0].mean()), float(mouth[:, 1].mean())
    mw = float(mouth[:, 0].max() - mouth[:, 0].min())
    mh = float(mouth[:, 1].max() - mouth[:, 1].min())
    half_w = max(mw * PATCH_WIDTH, 12.0)
    half_h = max(mh * PATCH_HEIGHT, 12.0)
    x0 = max(0, int(mcx - half_w))
    y0 = max(0, int(mcy - half_h))
    x1 = min(width, int(mcx + half_w))
    y1 = min(height, int(mcy + half_h))
    if x1 - x0 < 8 or y1 - y0 < 8:
        return None

    patch = aligned.crop((x0, y0, x1, y1))
    buf = io.BytesIO()
    patch.save(buf, format="PNG", optimize=True)
    return buf.getvalue(), {"x": x0, "y": y0, "w": x1 - x0, "h": y1 - y0}


def frame_key(org_id: str, avatar_id: str, viseme: str) -> str:
    return f"orgs/{org_id}/avatars/{avatar_id}/visemes/{viseme}.png"


def manifest_key(org_id: str, avatar_id: str) -> str:
    return f"orgs/{org_id}/avatars/{avatar_id}/visemes/manifest.json"


async def build_all(avatar, storage, image_bytes: bytes, rig: dict) -> int:
    """Generate, align and store every key frame. Returns how many survived.

    Frames are generated one at a time rather than concurrently: the provider
    rate-limits image requests, and a burst that trips the limit costs the
    whole set instead of one frame.
    """
    from app.services import imagegen
    from app.services.rig import VISEME_BLENDSHAPES

    if not imagegen.configured():
        raise VisemeFramesUnavailable("no image provider is configured")

    base_points = rig["points"]
    image_size = rig["image_size"]
    source, mime = imagegen.shrink_source(image_bytes)

    frames: list[dict] = []
    box: dict | None = None
    for viseme, description in KEY_VISEMES.items():
        prompt = (
            "Redraw this exact portrait with ONE change: the mouth. "
            f"The mouth must be {description}. "
            "Keep the identity, hairstyle, skin tone, lighting, camera angle, "
            "framing and background pixel-for-pixel identical — only the mouth "
            "and the immediately surrounding lip area may differ. Do not change "
            "the eyes, the expression of the eyes, or the head pose."
        )
        try:
            generated = await imagegen.generate_raw(prompt, source, mime)
        except Exception:
            logger.exception("viseme %s: generation failed", viseme)
            continue
        built = build_frame(generated, base_points, image_size)
        if built is None:
            continue
        png, geometry = built
        await storage.put_bytes(
            frame_key(avatar.org_id, avatar.id, viseme), png, "image/png"
        )
        box = geometry
        frames.append({"viseme": viseme, "shape": VISEME_BLENDSHAPES[viseme]})

    if not frames or box is None:
        return 0

    await storage.put_bytes(
        manifest_key(avatar.org_id, avatar.id),
        json.dumps({"box": box, "frames": frames}).encode(),
        "application/json",
    )
    return len(frames)
