// GENERATED by scripts/gen-api-types.mjs from the committed OpenAPI document
// (frontend/src/lib/api-schema.json). Do not edit: change the backend's
// schemas, export the document (backend/scripts/export_openapi.py), and
// run `npm run gen:api`.

export type AvatarKind = "photo" | "model3d";

export interface CueOut {
  a?: number;
  t: number;
  viseme: string;
}

export interface CueResponse {
  cues: CueOut[];
  duration_ms: number;
  word_marks: WordMark[];
}

/**
 * A published avatar, as a customer's widget is served it.
 */
export interface EmbedAvatarOut {
  /**
   * Absent from snapshots published before disclosures were recorded.
   */
  disclosure?: PublishedDisclosure;
  /**
   * The AI expression pictures; absent when there are none (the engine plays its animated expressions).
   */
  expressions?: PublishedExpressions;
  /**
   * How the head moves: a person's in depth, an animal's or a cartoon's as a layer.
   */
  face_type: "human" | "animal" | "cartoon";
  /**
   * `face` or `full`: the zoom when there is no scene.
   */
  framing: string;
  id: string;
  /**
   * The picture (a GLB for a 3D avatar), presigned.
   */
  image_url: string;
  kind: AvatarKind;
  /**
   * `background` (optional), `body` and `head`, presigned, when built.
   */
  layer_urls: Record<string, string> | null;
  /**
   * For kind `model3d`: the GLB, presigned.
   */
  model_url: string | null;
  /**
   * Null for the classic mouth with nothing of the owner's.
   */
  mouth: PublishedClassicMouth | PublishedContinuousMouth | null;
  name: string;
  /**
   * The rig, presigned; empty when the snapshot has none.
   */
  rig_url: string;
  /**
   * Null for a snapshot from before scenes.
   */
  scene: PublishedScene | null;
  /**
   * The 256 px thumbnail, presigned; may be empty.
   */
  thumbnail_url: string;
  voice: PublishedVoice | null;
}

/**
 * What an AI made or changed: the picture (`touchup`, `stylise`,
 * `regenerate`, `generate`), or only parts of the face (`teeth`,
 * `mouth_shapes`, `expressions`).
 */
export interface PublishedAiEdited {
  /**
   * Present when AI made the expression pictures shown.
   */
  expressions?: PublishedAiExpressions;
  mode: string;
  model: string | null;
  /**
   * Present when AI made the mouth shapes played.
   */
  mouth_shapes?: PublishedAiMouthShapes;
  /**
   * Present when AI made the teeth photo shown.
   */
  teeth?: PublishedAiTeeth;
}

export interface PublishedAiExpressions {
  made: number;
  model: string | null;
}

export interface PublishedAiMouthShapes {
  generated: number;
  model: string | null;
}

export interface PublishedAiTeeth {
  model: string | null;
}

/**
 * How the owner set a character mouth (an animation's or an animal's).
 */
export interface PublishedCharacter {
  jaw: number;
  style: "character" | "classic";
  teeth: "upper" | "none";
  tongue: boolean;
}

/**
 * The classic, drawn mouth, with the owner's character settings.
 */
export interface PublishedClassicMouth {
  character: PublishedCharacter;
  renderer: "classic";
}

/**
 * The photographic mouth.
 */
export interface PublishedContinuousMouth {
  /**
   * Always null: character settings are the classic mouth's.
   */
  character: null;
  /**
   * The avatar's own performance manifest; null for the bundled Reference motion.
   */
  motion_url: string | null;
  /**
   * The avatar's own teeth; null for the standard teeth, served beside the motion.
   */
  oral: PublishedOralUrls | null;
  profile: PublishedMouthProfile;
  renderer: "continuous";
}

/**
 * What visitors are told about the face.
 */
export interface PublishedDisclosure {
  /**
   * Null when no AI made or changed it.
   */
  ai_edited: PublishedAiEdited | null;
  line: "human" | "animal" | "cartoon";
}

/**
 * The avatar's AI expression pictures (services.expressions): the
 * manifest (per expression its picture's landmarks and where they go on
 * the face) and each picture, presigned.
 */
export interface PublishedExpressions {
  /**
   * By expression: happy, surprised, concerned, thinking, serious.
   */
  image_urls: Record<string, string>;
  manifest_url: string;
}

/**
 * The photographic mouth's fit to this face; a value the snapshot does
 * not set is the engine's default.
 */
export interface PublishedMouthProfile {
  /**
   * How far the jaw opens.
   */
  jawRange?: number;
  /**
   * How far the lips project.
   */
  lipProjection?: number;
  /**
   * Scale of the teeth.
   */
  teethScale?: number;
  /**
   * Vertical offset of the teeth.
   */
  teethY?: number;
  /**
   * Colour warmth of the mouth's inside.
   */
  warmth?: number;
}

/**
 * The avatar's own teeth photo and its rig, presigned.
 */
export interface PublishedOralUrls {
  image_url: string;
  rig_url: string;
}

/**
 * How far the view is moved from the engine's own placement, as
 * fractions of the view's size.
 */
export interface PublishedPan {
  x: number;
  y: number;
}

/**
 * The owner's framing: zoom 1 is the face view, 0 the whole picture,
 * above 1 closer in; the pan moves the view, the background sits behind a
 * cut-out.
 */
export interface PublishedScene {
  background: PublishedSceneBackground;
  pan: PublishedPan;
  zoom: number;
}

/**
 * What is behind a cut-out: nothing, a colour, or a picture.
 */
export interface PublishedSceneBackground {
  /**
   * `#rrggbb`, for kind `color`.
   */
  color?: string;
  /**
   * The picture, presigned, for kind `image`.
   */
  image_url?: string;
  kind: "transparent" | "color" | "image";
}

/**
 * The owner's published voice. A `data-voice` (or provider, locale)
 * attribute on the snippet still wins: that is per-site intent.
 */
export interface PublishedVoice {
  locale: string;
  provider: string;
  voice: string;
}

export interface SynthesizeResponse {
  audio_b64: string;
  audio_mime: string;
  cached: boolean;
  cues: CueOut[];
  duration_ms: number;
  /**
   * Each word's start in the audio, ms, when the request asked for them.
   */
  word_marks?: WordMark[];
}

/**
 * Where a word starts: its first character in the text, and its time, ms.
 */
export interface WordMark {
  char: number;
  t: number;
}
